version: "2"

services:
  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: example_pass

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
